version: "2"
services:
  ros2:
    build:
      context: .
      # args:
      #   - HTTP_PROXY=$HTTP_PROXY
      #   - http_proxy=$http_proxy
      #   - HTTPS_PROXY=$HTTPS_PROXY
      #   - https_proxy=$https_proxy
    ports:
      - "2018:2018"

    # environment:
    #   - HTTP_PROXY=$HTTP_PROXY
    #   - http_proxy=$http_proxy
    #   - HTTPS_PROXY=$HTTPS_PROXY
    #   - https_proxy=$https_proxy
